package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.PatientAdvocateAssignment;
import edu.ncsu.csc.iTrust2.models.User;

/**
 * Repository for interacting with PatientAdvocateAssignment model. Method
 * implementations generated by Spring
 *
 * @author ropeace
 */
public interface PatientAdvocateAssignmentRepository extends JpaRepository<PatientAdvocateAssignment, Long> {
    /**
     * Retrieves assignments for a given patient
     *
     * @param patient
     *            the patient to search with
     * @return a list of assignments
     */
    List<PatientAdvocateAssignment> findByPatient ( User patient );

    /**
     * Retrieves assignments for a given advocate
     *
     * @param patientAdvocate
     *            the advocate to search with
     * @return a list of assignments
     */
    List<PatientAdvocateAssignment> findByPatientAdvocate ( User patientAdvocate );

    /**
     * Retrieves one assignment based on patient and advocate
     *
     * @param patient
     *            the patient in the assignment
     * @param patientAdvocate
     *            the advocate in the assignment
     * @return the assignment
     */
    PatientAdvocateAssignment findByPatientAndPatientAdvocate ( User patient, User patientAdvocate );
}
